export const CANVAS_WIDTH = 960;
export const CANVAS_HEIGHT = 640;
export const TILE_SIZE = 48;
export const CHUNK_TILES = 8;
export const CHUNK_PIXELS = CHUNK_TILES * TILE_SIZE;
export const PLAYER_SPEED = 0.18;
export const NPC_SPEED = 0.072;
export const FRAME_SIZE = 48;
export const DIRECTIONS = ["down", "left", "right", "up"];
